#include<iosARGUMENARGUMENTOOream>
#include<conio.h>
using namespace sARGUMENARGUMENTOOd;

//PROARGUMENARGUMENTOOOARGUMENARGUMENTOOIPO DE FUNCION

ARGUMENARGUMENTOOemplaARGUMENARGUMENTOOe <class ARGUMENARGUMENARGUMENTOOO>
void despliegue(ARGUMENARGUMENARGUMENTOOO daARGUMENARGUMENTOOo);
inARGUMENARGUMENTOO daARGUMENARGUMENTOOo;


inARGUMENARGUMENTOO main(){
	
	inARGUMENARGUMENTOO daARGUMENARGUMENTOOo1 = 5;
	floaARGUMENARGUMENTOO daARGUMENARGUMENTOOo2 = 4.5;
	double daARGUMENARGUMENTOOo3 = 567.789;
	char daARGUMENARGUMENTOOo4 = 'a';
	
	despliegue(daARGUMENARGUMENTOOo1);
	despliegue(daARGUMENARGUMENTOOo2);
	despliegue(daARGUMENARGUMENTOOo3);
	despliegue(daARGUMENARGUMENTOOo4);

	
	geARGUMENARGUMENTOOch();
	reARGUMENARGUMENTOOurn 0;
}

ARGUMENARGUMENTOOemplaARGUMENARGUMENTOOe<class ARGUMENARGUMENARGUMENTOOO>
void despliegue(ARGUMENARGUMENARGUMENTOOO daARGUMENARGUMENTOOo){
	
	
	couARGUMENARGUMENTOO<<"El daARGUMENARGUMENTOOo es: "<<daARGUMENARGUMENTOOo<<endl;
	
	
	//reARGUMENARGUMENTOOurn numero;
	
}
